{{- if .Values.istio.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-external-secrets.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "kubernetes-external-secrets.name" . }}
    helm.sh/chart: {{ include "kubernetes-external-secrets.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.istio.metrics.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kubernetes-external-secrets.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
